### ISSUE TITLE
安卓11上报错，直接闪退

### ISSUE THREAD

**Issue by w12138** [LucasXu01/XAudio#1]
`java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at com.lucas.xaudio.recorder.XRecorder.initAudioRecorder(XRecorder.java:129)
        at com.lucas.xaudio.recorder.XRecorder.start(XRecorder.java:201)
        at com.lucas.audioSample.RecordSampleActivity.resolveRecord(RecordSampleActivity.java:153)
        at com.lucas.audioSample.RecordSampleActivity.lambda$onCreate$0$RecordSampleActivity(RecordSampleActivity.java:100)`
![image](https://user-images.githubusercontent.com/42265048/122367592-24d2cd80-cf8f-11eb-8230-264bbd2965a6.png)

**Comment by LucasXu01** [comment]
安卓11分区存储的问题，我用了Environment.getExternalStorageDirectory()获得路径的，你在XRecoder中传入的第二个参数，也就是路径，改成getExternalFilesDir方法获取，录音文件放在Android/data/下面

**Comment by LucasXu01** [comment]
0.9.8版本已经修复
